global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['node-app:3000']

  # - job_name: 'prod-app' #scrapping/pulling multiple jobs/targets using prometheus ~ possible
  #   scheme: https
  #   static_configs:
  #     - targets: ['week-25.100xdevs.com']

# while triggering emails on alerts via Grafana we need to add this, Grafana can't directly send alert emails
smtp_credentials: