apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 'nginx:latest'
          ports:
            - containerPort: 80

# `kubectl apply -f deployment-class.yml`
# deployment technically did not create 3 pods, under the hood deployment created replicaset and replicaset created 3 pods
# Deployment => Relicaset => 3 Pods