import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head><title>Deepika</title></head> */}
      <body className={inter.className}>
        <div className="p-4 border-b">
          Medium
        </div>
        {children}
      </body>
    </html>
  );
}
